### Login with known credentials into client
// @no-log
POST {{host}}/api/auth/login-client
Content-Type: application/json

{
  "nif": "{{test_user}}",
  "password": "{{test_password}}"
}

> {%
    client.test('Login with known credentials into client', function () {
        const status = response.status;
        client.assert(status === 200, `Response status is not 200 | Received ${status}`);
        const type = response.contentType.mimeType;
        client.assert(type === 'application/json', `Expected 'application/json' but received '${type}'`);
        client.global.set("auth_token", String(response.body));
    });
%}


### Try login into client with invalid credentials
// @no-log
POST {{host}}/api/auth/login-client
Content-Type: application/json

{
  "nif": "{{test_user}}",
  "password": "test0"
}

> {%
    client.test('Try login into client with invalid credentials', function () {
        const status = response.status;
        client.assert(status === 401, `Response status is not 401 | Received ${status}`);
        const type = response.contentType.mimeType;
        client.assert(type === 'application/json', `Expected 'application/json' but received '${type}'`);
        client.assert(String(response.body) === 'Credenciais de login inválidas.');
    });
%}

### Change password with know credentials
// @no-log
PATCH {{host}}/api/auth/change-password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "oldPassword": "{{test_password}}",
  "newPassword": "test2",
  "confirmPassword": "test2"
}

> {%
    client.test('Change password with know credentials', function () {
        const status = response.status;
        client.assert(status === 200, `Response status is not 200 | Received ${status}`);
        const type = response.contentType.mimeType;
        client.assert(type === 'application/json', `Expected 'application/json' but received '${type}'`);

        const old_token = client.global.get('auth_token');
        const new_token = String(response.body);
        client.assert(new_token && String(old_token) !== new_token, 'The old token is expected to be different from the new token');
        client.global.set("auth_token", new_token);
    });
%}


### Change password with know old credentials
// @no-log
PATCH {{host}}/api/auth/change-password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "oldPassword": "{{test_password}}",
  "newPassword": "test2",
  "confirmPassword": "test2"
}

> {%
    client.test('Change password with know old credentials', function () {
        const status = response.status;
        client.assert(status === 400, `Response status is not 400 | Received ${status}`);
        const type = response.contentType.mimeType;
        client.assert(type === 'application/json', `Expected 'application/json' but received '${type}'`);
        client.assert(String(response.body) === 'A senha antiga está errada ou a nova senha e a confirmação da senha não correspondem.');
    });
%}


### Change password with unmatch confirm password
// @no-log
PATCH {{host}}/api/auth/change-password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "oldPassword": "test2",
  "newPassword": "test1",
  "confirmPassword": "test"
}

> {%
    client.test('Change password with unmatch confirm password', function () {
        const status = response.status;
        client.assert(status === 400, `Response status is not 400 | Received ${status}`);
        const type = response.contentType.mimeType;
        client.assert(type === 'application/json', `Expected 'application/json' but received '${type}'`);
        client.assert(String(response.body) === 'A senha antiga está errada ou a nova senha e a confirmação da senha não correspondem.');
    });
%}


### Change password back to original
// @no-log
PATCH {{host}}/api/auth/change-password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "oldPassword": "test2",
  "newPassword": "{{test_password}}",
  "confirmPassword": "{{test_password}}"
}

> {%
    client.test('Change password back to original', function () {
        const status = response.status;
        client.assert(status === 200, `Response status is not 200 | Received ${status}`);
        client.global.set("auth_token", String(response.body));
    });
%}